# Generated by Django 3.1.1 on 2020-09-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntary',
            options={'ordering': ['-name'], 'verbose_name': 'Voluntario'},
        ),
    ]
