# Generated by Django 3.1.1 on 2020-09-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_action', models.CharField(max_length=300, verbose_name='Nome da Ação')),
                ('institution_organizing', models.CharField(max_length=300, verbose_name='Nome da Instituição')),
                ('city', models.CharField(max_length=200, verbose_name='Cidade')),
                ('neighborhood', models.CharField(max_length=200, verbose_name='Bairro')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Açoes',
                'ordering': ['name_action'],
            },
        ),
    ]
