# Generated by Django 3.1.1 on 2020-09-11 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0002_auto_20200910_2225'),
        ('açoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='voluntary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voluntario.voluntary'),
            preserve_default=False,
        ),
    ]
