# Generated by Django 3.1.1 on 2020-09-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('açoes', '0002_actions_voluntary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='voluntary',
            new_name='incluir_voluntario',
        ),
    ]
